uploads = []
generated = []

[[outputs]]
id = "ALJpxquPCEozQMTSNOx43"
uri = "file://reports/cartera_cobranza_Gabriel_Jaime_Hoyos_Guzman_20260427.xlsx"
type = "table"
title = "Cartera Gabriel - 27/04/2026"

[[outputs]]
id = "aWRFq1Gwrm7HRd-sv1Qoo"
uri = "file://reports/cartera_cobranza_Jhonatan_Jose_Ruiz_Valera_20260427.xlsx"
type = "table"
title = "Cartera Jhonatan - 27/04/2026"

[[outputs]]
id = "i6-rhu-rqC5sq1Yxltc61"
uri = "file://reports/cartera_cobranza_Ernesto_Antonio_Quintiliani_Gutiérrez_20260427.xlsx"
type = "table"
title = "Cartera Ernesto - 27/04/2026"

[[outputs]]
id = "yQ-7P0jZTKK-THdHfPy5L"
uri = "file://reports/cartera_cobranza_Pablo_Vicente_Pinto_Rico_20260427.xlsx"
type = "table"
title = "Cartera Pablo - 27/04/2026"

[[outputs]]
id = "UCWTRZDBG4k6w5CQ4cAhW"
uri = "file://reports/cartera_cobranza_Jesus_Ernesto_Gonzalez_Gimenez_20260427.xlsx"
type = "table"
title = "Cartera Jesus - 27/04/2026"

[[outputs]]
id = "wiJvNC7nMRktr_7GG3utw"
uri = "file://reportes_cliente/Reporte_Mejoras_BI_VLSur.docx"
type = "word_document"
title = "Reporte de Estado y Mejoras - Plataforma BI VLSur"

[[outputs]]
id = "3-jQQpvSXwLYymN2VXQme"
uri = "file://reportes_cliente/Reporte_Mejoras_BI_VLSur.pdf"
type = "pdf"
title = "Reporte de Estado y Mejoras - Plataforma BI VLSur (PDF)"
